#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd ~/src/nixpkgs

git reset --hard HEAD

git clean -f -x -d .

rm "$SCRIPT_DIR"/{non-existent,moved}

# mv pkgs/* .

# mkdir -p pkgs/auto

cd pkgs/top-level
rg -n '^  ([^ =]*) *= *callPackage *([^ ]*/[^ ]*) *\{ *\} *;' all-packages.nix -or '$1:$2' \
  | while IFS=: read line attr file; do
    slashes=$(realpath "$file" | tr -dc '/' | wc -c)
    # Sorting by number of slashes in the path means a depth-first traversal
    # This is needed so that we don't e.g. remove the pkgs/shells/zsh directory (whose `default.nix` the `zsh` attribute is declared as) before moving e.g. pkgs/shells/zsh/zsh-completions
    echo "$slashes $line $attr $file"
  done \
  | sort -k1 -r -n \
  | while read slashes line attr file; do
    if [[ -f "$file" ]]; then
      mkdir ../auto/"$attr"
      mv "$file" ../auto/"$attr"/default.nix
    else
      mv "$file" ../auto/"$attr"
    fi
    echo "$line"
  done \
  | sort -n -r \
  | while read line; do
    sed -i "${line}d" all-packages.nix
  done

# Remove consecutive newlines, hacky :3
for i in $(seq 10); do
  sed -i -z 's/\n\n\n/\n\n/g' all-packages.nix
done
